"""empty message

Revision ID: 129511785aaa
Revises: 543037b765f6
Create Date: 2020-05-04 01:28:31.372718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '129511785aaa'
down_revision = '543037b765f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('todos', sa.Column('todolist_id', sa.Integer()))
    op.create_foreign_key(None, 'todos', 'todo_lists', ['todolist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'todolist_id')
    op.drop_table('todo_lists')
    # ### end Alembic commands ###
