"""empty message

Revision ID: 6f99ddcaed73
Revises: ef367b971af0
Create Date: 2020-05-04 16:48:33.528516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f99ddcaed73'
down_revision = 'ef367b971af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('todos_todolist_id_fkey', 'todos', type_='foreignkey')
    op.create_foreign_key(None, 'todos', 'todo_lists', ['todolist_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.create_foreign_key('todos_todolist_id_fkey', 'todos', 'todo_lists', ['todolist_id'], ['id'])
    # ### end Alembic commands ###
